@echo off
echo Starting HappyTravell with database support...
echo Compiling AbsoluteLayout classes first...
javac -cp "lib/mysql-connector-j-9.2.0.jar;lib/mail.jar;src" lib/org/netbeans/lib/awtextra/AbsoluteLayout.java
echo Compiling main application...
javac -cp "lib/mysql-connector-j-9.2.0.jar;lib/mail.jar;lib/org;src" src/happytravell/HappyTravell.java
echo Running application...
java -cp "lib/mysql-connector-j-9.2.0.jar;lib/mail.jar;lib/org;src" happytravell.HappyTravell
pause 