/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package happytravell.view;

import java.awt.Image;
import java.awt.event.ActionListener;
import java.awt.event.MouseListener;
import javax.swing.ImageIcon;
import javax.swing.JLabel;

/**
 *
 * @author Acer
 */
public class AdmindashboardView extends javax.swing.JFrame {

    /**
     * Creates new form AdmindashboardView
     */
    public AdmindashboardView() {
        initComponents();
        scaleImage1();
        scaleImage2();
        scaleImage3();
        scaleImage4();
        scaleImage5();
        scaleImage6();
        scaleImage7();
        scaleImage8();
        scaleImage9();

    }
    
    public void scaleImage1(){
        ImageIcon icon1 = new ImageIcon(getClass().getResource("/image/dashboard.png"));
        //scaling image to fit in the hlabel.
        Image img1 = icon1.getImage();
        Image imgScale = img1.getScaledInstance(dashboardIcon.getWidth(), dashboardIcon.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon scaledIcon = new ImageIcon(imgScale);
        dashboardIcon.setIcon(scaledIcon);
    }
    public void scaleImage2(){
        ImageIcon icon1 = new ImageIcon(getClass().getResource("/image/booking.png"));
        //scaling image to fit in the hlabel.
        Image img1 = icon1.getImage();
        Image imgScale = img1.getScaledInstance(bookingIcon.getWidth(), bookingIcon.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon scaledIcon = new ImageIcon(imgScale);
        bookingIcon.setIcon(scaledIcon);
    }
    public void scaleImage3(){
        ImageIcon icon1 = new ImageIcon(getClass().getResource("/image/directions.png"));
        //scaling image to fit in the hlabel.
        Image img1 = icon1.getImage();
        Image imgScale = img1.getScaledInstance(routeIcon.getWidth(), routeIcon.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon scaledIcon = new ImageIcon(imgScale);
        routeIcon.setIcon(scaledIcon);
    }
    public void scaleImage4(){
        ImageIcon icon1 = new ImageIcon(getClass().getResource("/image/tickets.png"));
        //scaling image to fit in the hlabel.
        Image img1 = icon1.getImage();
        Image imgScale = img1.getScaledInstance(busTicketIcon.getWidth(), busTicketIcon.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon scaledIcon = new ImageIcon(imgScale);
        busTicketIcon.setIcon(scaledIcon);
    }
    public void scaleImage5(){
        ImageIcon icon1 = new ImageIcon(getClass().getResource("/image/front-of-bus.png"));
        //scaling image to fit in the hlabel.
        Image img1 = icon1.getImage();
        Image imgScale = img1.getScaledInstance(vehiclesIcon.getWidth(), vehiclesIcon.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon scaledIcon = new ImageIcon(imgScale);
        vehiclesIcon.setIcon(scaledIcon);
    }
    public void scaleImage6(){
        ImageIcon icon1 = new ImageIcon(getClass().getResource("/image/user.png"));
        //scaling image to fit in the hlabel.
        Image img1 = icon1.getImage();
        Image imgScale = img1.getScaledInstance(profileIcon.getWidth(), profileIcon.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon scaledIcon = new ImageIcon(imgScale);
        profileIcon.setIcon(scaledIcon);
    }
    public void scaleImage7(){
        ImageIcon icon1 = new ImageIcon(getClass().getResource("/image/logout.png"));
        //scaling image to fit in the hlabel.
        Image img1 = icon1.getImage();
        Image imgScale = img1.getScaledInstance(logoutIcon.getWidth(), logoutIcon.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon scaledIcon = new ImageIcon(imgScale);
        logoutIcon.setIcon(scaledIcon);
    }
    public void scaleImage8(){
        ImageIcon icon1 = new ImageIcon(getClass().getResource("/image/happy.png"));
        //scaling image to fit in the hlabel.
        Image img1 = icon1.getImage();
        Image imgScale = img1.getScaledInstance(logoIcon.getWidth(), logoIcon.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon scaledIcon = new ImageIcon(imgScale);
        logoIcon.setIcon(scaledIcon);
    }
    public void scaleImage9(){
        ImageIcon icon1 = new ImageIcon(getClass().getResource("/image/ringing.png"));
        //scaling image to fit in the hlabel.
        Image img1 = icon1.getImage();
        Image imgScale = img1.getScaledInstance(notificationIcon.getWidth(), notificationIcon.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon scaledIcon = new ImageIcon(imgScale);
        notificationIcon.setIcon(scaledIcon);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel11 = new javax.swing.JPanel();
        jToolBar1 = new javax.swing.JToolBar();
        TravelerDetailsPanel = new javax.swing.JPanel();
        placePanel = new javax.swing.JPanel();
        pokharaPanelButton = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        mustangPanelButton = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        kathmanduPanelButton = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        reviewsButton = new javax.swing.JButton();
        travellersButton = new javax.swing.JButton();
        travellingButton = new javax.swing.JButton();
        placesButton = new javax.swing.JButton();
        notificationIcon = new javax.swing.JLabel();
        DashDetailsPanel = new javax.swing.JPanel();
        logoutIcon = new javax.swing.JLabel();
        profileIcon = new javax.swing.JLabel();
        vehiclesIcon = new javax.swing.JLabel();
        busTicketIcon = new javax.swing.JLabel();
        happyTravelLabel = new javax.swing.JLabel();
        routeIcon = new javax.swing.JLabel();
        bookingIcon = new javax.swing.JLabel();
        dashboardIcon = new javax.swing.JLabel();
        logoIcon = new javax.swing.JLabel();
        dashboardLabel = new javax.swing.JLabel();
        bookingDetailsLabel = new javax.swing.JLabel();
        routeDetailsLabel = new javax.swing.JLabel();
        busTicketsLabel = new javax.swing.JLabel();
        vehiclesDetailsLabel = new javax.swing.JLabel();
        profileLabel = new javax.swing.JLabel();
        logOutLabel = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jToolBar1.setRollover(true);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        TravelerDetailsPanel.setBackground(new java.awt.Color(255, 242, 227));
        TravelerDetailsPanel.setLayout(null);

        placePanel.setBackground(new java.awt.Color(200, 143, 75));
        placePanel.setLayout(null);

        pokharaPanelButton.setBackground(new java.awt.Color(222, 183, 154));
        pokharaPanelButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        pokharaPanelButton.setPreferredSize(new java.awt.Dimension(640, 360));
        pokharaPanelButton.setLayout(null);

        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/pokhara.jpg"))); // NOI18N
        pokharaPanelButton.add(jLabel22);
        jLabel22.setBounds(8, 8, -1, 126);

        jLabel19.setFont(new java.awt.Font("Candara", 1, 12)); // NOI18N
        jLabel19.setText("Pokhara");
        pokharaPanelButton.add(jLabel19);
        jLabel19.setBounds(55, 140, 43, -1);

        jLabel23.setFont(new java.awt.Font("Candara", 2, 12)); // NOI18N
        jLabel23.setText("Pokhara is a city on Phewa ");
        pokharaPanelButton.add(jLabel23);
        jLabel23.setBounds(8, 156, 139, -1);

        jLabel24.setFont(new java.awt.Font("Candara", 2, 12)); // NOI18N
        jLabel24.setText("Lake, in central Nepal.");
        pokharaPanelButton.add(jLabel24);
        jLabel24.setBounds(8, 177, 139, -1);

        placePanel.add(pokharaPanelButton);
        pokharaPanelButton.setBounds(6, 21, 155, 214);

        mustangPanelButton.setBackground(new java.awt.Color(222, 183, 154));
        mustangPanelButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        mustangPanelButton.setPreferredSize(new java.awt.Dimension(640, 360));
        mustangPanelButton.setLayout(null);

        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/mustang.jpg"))); // NOI18N
        mustangPanelButton.add(jLabel21);
        jLabel21.setBounds(8, 8, -1, 135);

        jLabel11.setFont(new java.awt.Font("Candara", 1, 12)); // NOI18N
        jLabel11.setText("Mustang");
        mustangPanelButton.add(jLabel11);
        jLabel11.setBounds(57, 149, -1, -1);

        jLabel26.setFont(new java.awt.Font("Candara", 2, 12)); // NOI18N
        jLabel26.setText("The district is home to ");
        mustangPanelButton.add(jLabel26);
        jLabel26.setBounds(8, 170, -1, -1);

        jLabel29.setFont(new java.awt.Font("Candara", 2, 12)); // NOI18N
        jLabel29.setText("Muktinath Temple.");
        mustangPanelButton.add(jLabel29);
        jLabel29.setBounds(8, 191, -1, -1);

        placePanel.add(mustangPanelButton);
        mustangPanelButton.setBounds(173, 21, 155, 214);

        kathmanduPanelButton.setBackground(new java.awt.Color(222, 183, 154));
        kathmanduPanelButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        kathmanduPanelButton.setPreferredSize(new java.awt.Dimension(640, 360));
        kathmanduPanelButton.setLayout(null);

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/kathmandu.jpg"))); // NOI18N
        kathmanduPanelButton.add(jLabel18);
        jLabel18.setBounds(8, 2, -1, -1);

        jLabel27.setFont(new java.awt.Font("Candara", 1, 12)); // NOI18N
        jLabel27.setText("Kathmandu");
        kathmanduPanelButton.add(jLabel27);
        jLabel27.setBounds(46, 146, -1, -1);

        jLabel28.setFont(new java.awt.Font("Candara", 2, 12)); // NOI18N
        jLabel28.setText("Kathmandu is best known");
        kathmanduPanelButton.add(jLabel28);
        jLabel28.setBounds(8, 167, -1, -1);

        jLabel30.setFont(new java.awt.Font("Candara", 2, 12)); // NOI18N
        jLabel30.setText("For its historical sights.");
        kathmanduPanelButton.add(jLabel30);
        jLabel30.setBounds(8, 188, -1, -1);

        placePanel.add(kathmanduPanelButton);
        kathmanduPanelButton.setBounds(334, 21, 161, 214);

        jLabel17.setFont(new java.awt.Font("Candara", 1, 14)); // NOI18N
        jLabel17.setText("Popular Destinations near you");
        placePanel.add(jLabel17);
        jLabel17.setBounds(6, 3, 211, -1);

        TravelerDetailsPanel.add(placePanel);
        placePanel.setBounds(6, 54, -1, -1);

        jLabel2.setFont(new java.awt.Font("Candara", 1, 18)); // NOI18N
        jLabel2.setText("Welcome Admin, ");
        TravelerDetailsPanel.add(jLabel2);
        jLabel2.setBounds(6, 6, 153, -1);

        jLabel3.setFont(new java.awt.Font("Candara", 2, 12)); // NOI18N
        jLabel3.setText("Track and manage bookings, places and more..");
        TravelerDetailsPanel.add(jLabel3);
        jLabel3.setBounds(6, 27, -1, -1);

        reviewsButton.setBackground(new java.awt.Color(194, 133, 72));
        reviewsButton.setFont(new java.awt.Font("Candara", 1, 12)); // NOI18N
        reviewsButton.setText("Reviews");
        reviewsButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        reviewsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reviewsButtonActionPerformed(evt);
            }
        });
        TravelerDetailsPanel.add(reviewsButton);
        reviewsButton.setBounds(390, 300, 115, 53);

        travellersButton.setBackground(new java.awt.Color(194, 133, 72));
        travellersButton.setFont(new java.awt.Font("Candara", 1, 12)); // NOI18N
        travellersButton.setText("Travellers");
        travellersButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        travellersButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                travellersButtonActionPerformed(evt);
            }
        });
        TravelerDetailsPanel.add(travellersButton);
        travellersButton.setBounds(10, 300, 115, 53);

        travellingButton.setBackground(new java.awt.Color(194, 133, 72));
        travellingButton.setFont(new java.awt.Font("Candara", 1, 12)); // NOI18N
        travellingButton.setText("Travelling");
        travellingButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        travellingButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                travellingButtonActionPerformed(evt);
            }
        });
        TravelerDetailsPanel.add(travellingButton);
        travellingButton.setBounds(135, 300, 115, 53);

        placesButton.setBackground(new java.awt.Color(194, 133, 72));
        placesButton.setFont(new java.awt.Font("Candara", 1, 12)); // NOI18N
        placesButton.setText("Places");
        placesButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        placesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                placesButtonActionPerformed(evt);
            }
        });
        TravelerDetailsPanel.add(placesButton);
        placesButton.setBounds(265, 300, 115, 53);

        notificationIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/ringing.png"))); // NOI18N
        TravelerDetailsPanel.add(notificationIcon);
        notificationIcon.setBounds(470, 5, 25, 25);
        notificationIcon.getAccessibleContext().setAccessibleName("");

        getContentPane().add(TravelerDetailsPanel);
        TravelerDetailsPanel.setBounds(130, 0, 510, 360);

        DashDetailsPanel.setBackground(new java.awt.Color(241, 215, 184));
        DashDetailsPanel.setLayout(null);

        logoutIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/logout.png"))); // NOI18N
        DashDetailsPanel.add(logoutIcon);
        logoutIcon.setBounds(10, 295, 18, 18);
        logoutIcon.getAccessibleContext().setAccessibleName("");

        profileIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/user.png"))); // NOI18N
        profileIcon.setText("jLabel1");
        DashDetailsPanel.add(profileIcon);
        profileIcon.setBounds(10, 255, 18, 18);

        vehiclesIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/front-of-bus.png"))); // NOI18N
        DashDetailsPanel.add(vehiclesIcon);
        vehiclesIcon.setBounds(10, 216, 18, 18);

        busTicketIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/tickets.png"))); // NOI18N
        DashDetailsPanel.add(busTicketIcon);
        busTicketIcon.setBounds(10, 178, 18, 18);

        happyTravelLabel.setFont(new java.awt.Font("Candara", 1, 12)); // NOI18N
        happyTravelLabel.setText("Happy Travels");
        DashDetailsPanel.add(happyTravelLabel);
        happyTravelLabel.setBounds(50, 15, 80, -1);

        routeIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/directions.png"))); // NOI18N
        DashDetailsPanel.add(routeIcon);
        routeIcon.setBounds(10, 140, 18, 18);

        bookingIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/booking.png"))); // NOI18N
        DashDetailsPanel.add(bookingIcon);
        bookingIcon.setBounds(10, 97, 18, 18);
        bookingIcon.getAccessibleContext().setAccessibleName("");

        dashboardIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/dashboard.png"))); // NOI18N
        dashboardIcon.setText("jLabel1");
        DashDetailsPanel.add(dashboardIcon);
        dashboardIcon.setBounds(10, 58, 18, 18);

        logoIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/happy.png"))); // NOI18N
        logoIcon.setFocusCycleRoot(true);
        DashDetailsPanel.add(logoIcon);
        logoIcon.setBounds(-35, -5, 120, 50);
        logoIcon.getAccessibleContext().setAccessibleName("");

        dashboardLabel.setFont(new java.awt.Font("Candara", 1, 12)); // NOI18N
        dashboardLabel.setText("  Dashboard");
        DashDetailsPanel.add(dashboardLabel);
        dashboardLabel.setBounds(30, 60, 80, -1);

        bookingDetailsLabel.setFont(new java.awt.Font("Candara", 1, 12)); // NOI18N
        bookingDetailsLabel.setText("  Booking Details");
        DashDetailsPanel.add(bookingDetailsLabel);
        bookingDetailsLabel.setBounds(30, 100, 100, -1);

        routeDetailsLabel.setFont(new java.awt.Font("Candara", 1, 12)); // NOI18N
        routeDetailsLabel.setText("  Route Details");
        DashDetailsPanel.add(routeDetailsLabel);
        routeDetailsLabel.setBounds(30, 140, 90, 20);

        busTicketsLabel.setFont(new java.awt.Font("Candara", 1, 12)); // NOI18N
        busTicketsLabel.setText("  Bus Tickets");
        DashDetailsPanel.add(busTicketsLabel);
        busTicketsLabel.setBounds(36, 182, 60, -1);

        vehiclesDetailsLabel.setFont(new java.awt.Font("Candara", 1, 12)); // NOI18N
        vehiclesDetailsLabel.setText("  Vehicles Details");
        DashDetailsPanel.add(vehiclesDetailsLabel);
        vehiclesDetailsLabel.setBounds(31, 220, 90, -1);

        profileLabel.setFont(new java.awt.Font("Candara", 1, 12)); // NOI18N
        profileLabel.setText("  Profile");
        DashDetailsPanel.add(profileLabel);
        profileLabel.setBounds(40, 260, 50, -1);

        logOutLabel.setFont(new java.awt.Font("Candara", 1, 12)); // NOI18N
        logOutLabel.setText("  Log Out");
        DashDetailsPanel.add(logOutLabel);
        logOutLabel.setBounds(40, 300, -1, -1);

        getContentPane().add(DashDetailsPanel);
        DashDetailsPanel.setBounds(0, 0, 130, 360);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void reviewsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reviewsButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_reviewsButtonActionPerformed

    private void travellersButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_travellersButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_travellersButtonActionPerformed

    private void travellingButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_travellingButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_travellingButtonActionPerformed

    private void placesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_placesButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_placesButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdmindashboardView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdmindashboardView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdmindashboardView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdmindashboardView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdmindashboardView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel DashDetailsPanel;
    private javax.swing.JPanel TravelerDetailsPanel;
    private javax.swing.JLabel bookingDetailsLabel;
    private javax.swing.JLabel bookingIcon;
    private javax.swing.JLabel busTicketIcon;
    private javax.swing.JLabel busTicketsLabel;
    private javax.swing.JLabel dashboardIcon;
    private javax.swing.JLabel dashboardLabel;
    private javax.swing.JLabel happyTravelLabel;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JPanel kathmanduPanelButton;
    private javax.swing.JLabel logOutLabel;
    private javax.swing.JLabel logoIcon;
    private javax.swing.JLabel logoutIcon;
    private javax.swing.JPanel mustangPanelButton;
    private javax.swing.JLabel notificationIcon;
    private javax.swing.JPanel placePanel;
    private javax.swing.JButton placesButton;
    private javax.swing.JPanel pokharaPanelButton;
    private javax.swing.JLabel profileIcon;
    private javax.swing.JLabel profileLabel;
    private javax.swing.JButton reviewsButton;
    private javax.swing.JLabel routeDetailsLabel;
    private javax.swing.JLabel routeIcon;
    private javax.swing.JButton travellersButton;
    private javax.swing.JButton travellingButton;
    private javax.swing.JLabel vehiclesDetailsLabel;
    private javax.swing.JLabel vehiclesIcon;
    // End of variables declaration//GEN-END:variables

    
    public void PlacesNavigation(ActionListener listener){
        placesButton.addActionListener(listener);
    }
    public void TravellersNavigation(ActionListener listener){
        travellersButton.addActionListener(listener);
    }
    public void TravellingNavigation(ActionListener listener){
        travellingButton.addActionListener(listener);
    }
    public void ReviewsNavigation(ActionListener listener){
        reviewsButton.addActionListener(listener);
    }
    public void DashboardNavigation(MouseListener listener){
        dashboardLabel.addMouseListener(listener);
    }
    public JLabel getDashboardlabel(){
        return dashboardLabel;
    }
    public void BookingDetailsNavigation(MouseListener listener){
        bookingDetailsLabel.addMouseListener(listener);
    }
    public JLabel getBookingDetailslabel(){
        return bookingDetailsLabel;
    }
    public void RouteDetailsNavigation(MouseListener listener){
        routeDetailsLabel.addMouseListener(listener);
    }
    public JLabel getRouteDetailslabel(){
        return routeDetailsLabel;
    }
    public void BusTicketsNavigation(MouseListener listener){
        busTicketsLabel.addMouseListener(listener);
    }
    public JLabel getBusTicketslabel(){
        return busTicketsLabel;
    }
    public void VehiclesDetailsNavigation(MouseListener listener){
        vehiclesDetailsLabel.addMouseListener(listener);
    }
    public JLabel getVehiclesDetailslabel(){
        return vehiclesDetailsLabel;
    }
    public void ProfileNavigation(MouseListener listener){
        profileLabel.addMouseListener(listener);
    }
    public JLabel getProfilelabel(){
        return profileLabel;
    }
    public void LogOutNavigation(MouseListener listener){
        logOutLabel.addMouseListener(listener);
    }
    public JLabel getLogOutlabel(){
        return logOutLabel;
    }
    
  
}
