/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package happytravell.view;

import java.awt.event.ActionListener;
import javax.swing.JLabel;

/**
 *
 * @author Acer
 */
public class AdminRegisterView extends javax.swing.JFrame {

    private JLabel jLabel1;

    /**
     * Creates new form Register
     */
    public AdminRegisterView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField2 = new javax.swing.JTextField();
        RegisterLabel = new javax.swing.JLabel();
        lastnameTextField = new javax.swing.JTextField();
        firstnameTextField = new javax.swing.JTextField();
        usernameTextField = new javax.swing.JTextField();
        registerButton = new javax.swing.JButton();
        backButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        lastnameLabel = new javax.swing.JLabel();
        setUsernamelabel = new javax.swing.JLabel();
        emailLabel = new javax.swing.JLabel();
        phonenumberLabel = new javax.swing.JLabel();
        addressLabel = new javax.swing.JLabel();
        setPassword = new javax.swing.JLabel();
        confirmpasswordlabel = new javax.swing.JLabel();
        firstnameLabel = new javax.swing.JLabel();
        emailTextField = new javax.swing.JTextField();
        phoneNumberTextField = new javax.swing.JTextField();
        addressTextField = new javax.swing.JTextField();
        setPasswordField = new javax.swing.JPasswordField();
        confirmPasswordField = new javax.swing.JPasswordField();
        confirmShowButton = new javax.swing.JToggleButton();
        showButton = new javax.swing.JToggleButton();
        jLabel3 = new javax.swing.JLabel();

        jTextField2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextField2.setText("  Set Username");
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        RegisterLabel.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        RegisterLabel.setForeground(new java.awt.Color(204, 102, 0));
        RegisterLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        RegisterLabel.setText("Admin Registration");
        getContentPane().add(RegisterLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 50, 290, 31));

        lastnameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lastnameTextFieldActionPerformed(evt);
            }
        });
        getContentPane().add(lastnameTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 160, 180, 30));

        firstnameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstnameTextFieldActionPerformed(evt);
            }
        });
        getContentPane().add(firstnameTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 110, 180, 30));

        usernameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameTextFieldActionPerformed(evt);
            }
        });
        getContentPane().add(usernameTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 210, 180, 30));

        registerButton.setBackground(new java.awt.Color(255, 153, 51));
        registerButton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        registerButton.setText("Register");
        getContentPane().add(registerButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 520, 180, -1));

        backButton.setBackground(new java.awt.Color(255, 153, 51));
        backButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        backButton.setText("Back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });
        getContentPane().add(backButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 522, 80, 30));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 72, -1, -1));

        lastnameLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lastnameLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lastnameLabel.setText(" Last name");
        getContentPane().add(lastnameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 160, 90, 30));

        setUsernamelabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        setUsernamelabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        setUsernamelabel.setText(" Set Username");
        getContentPane().add(setUsernamelabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 210, 100, 30));

        emailLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        emailLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        emailLabel.setText(" Email");
        getContentPane().add(emailLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 260, 50, 30));

        phonenumberLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        phonenumberLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        phonenumberLabel.setText("Phone number");
        getContentPane().add(phonenumberLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 310, 110, 30));

        addressLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        addressLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        addressLabel.setText(" Address");
        getContentPane().add(addressLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 360, 80, 30));

        setPassword.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        setPassword.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        setPassword.setText(" Set Password");
        getContentPane().add(setPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 410, 110, 30));

        confirmpasswordlabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        confirmpasswordlabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        confirmpasswordlabel.setText("Confirm Password");
        getContentPane().add(confirmpasswordlabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 460, 130, 30));

        firstnameLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        firstnameLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        firstnameLabel.setText(" First name");
        getContentPane().add(firstnameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 110, 80, 30));

        emailTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailTextFieldActionPerformed(evt);
            }
        });
        getContentPane().add(emailTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 260, 180, 30));

        phoneNumberTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phoneNumberTextFieldActionPerformed(evt);
            }
        });
        getContentPane().add(phoneNumberTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 310, 180, 30));

        addressTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addressTextFieldActionPerformed(evt);
            }
        });
        getContentPane().add(addressTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 360, 180, 30));

        setPasswordField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setPasswordFieldActionPerformed(evt);
            }
        });
        getContentPane().add(setPasswordField, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 410, 180, 30));

        confirmPasswordField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmPasswordFieldActionPerformed(evt);
            }
        });
        getContentPane().add(confirmPasswordField, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 460, 180, 30));

        confirmShowButton.setText("Show");
        confirmShowButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmShowButtonActionPerformed(evt);
            }
        });
        getContentPane().add(confirmShowButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 460, 80, 30));

        showButton.setText("Show");
        showButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showButtonActionPerformed(evt);
            }
        });
        getContentPane().add(showButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 410, 80, 30));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/LoginFinal.png"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 880, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void firstnameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firstnameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_firstnameTextFieldActionPerformed

    private void usernameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernameTextFieldActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_backButtonActionPerformed

    private void lastnameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lastnameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lastnameTextFieldActionPerformed

    private void emailTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailTextFieldActionPerformed

    private void phoneNumberTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phoneNumberTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_phoneNumberTextFieldActionPerformed

    private void addressTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addressTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addressTextFieldActionPerformed

    private void confirmPasswordFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmPasswordFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_confirmPasswordFieldActionPerformed

    private void setPasswordFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_setPasswordFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_setPasswordFieldActionPerformed


    private void confirmShowButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmShowButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_confirmShowButtonActionPerformed

    private void showButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_showButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminRegisterView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminRegisterView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminRegisterView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminRegisterView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminRegisterView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel RegisterLabel;
    private javax.swing.JLabel addressLabel;
    private javax.swing.JTextField addressTextField;
    private javax.swing.JButton backButton;
    private javax.swing.JPasswordField confirmPasswordField;
    private javax.swing.JToggleButton confirmShowButton;
    private javax.swing.JLabel confirmpasswordlabel;
    private javax.swing.JLabel emailLabel;
    private javax.swing.JTextField emailTextField;
    private javax.swing.JLabel firstnameLabel;
    private javax.swing.JTextField firstnameTextField;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JLabel lastnameLabel;
    private javax.swing.JTextField lastnameTextField;
    private javax.swing.JTextField phoneNumberTextField;
    private javax.swing.JLabel phonenumberLabel;
    private javax.swing.JButton registerButton;
    private javax.swing.JLabel setPassword;
    private javax.swing.JPasswordField setPasswordField;
    private javax.swing.JLabel setUsernamelabel;
    private javax.swing.JToggleButton showButton;
    private javax.swing.JTextField usernameTextField;
    // End of variables declaration//GEN-END:variables
public void registerAdmin(ActionListener listener){
        registerButton.addActionListener(listener);
    }
    public void mainpageBack(ActionListener listener){
        backButton.addActionListener(listener);
    }

    public javax.swing.JToggleButton getShowButton() {
    return showButton;
    }
    public javax.swing.JToggleButton getConfirmShowButton() {
    return confirmShowButton;
    }

    
    public javax.swing.JTextField getFirstNameTextField(){
        return firstnameTextField;
    }
    public javax.swing.JTextField getLastNameTextField(){
        return lastnameTextField;
    }
    public javax.swing.JTextField getUsernameTextField(){
        return usernameTextField;
    }
    public javax.swing.JTextField getEmailTextField(){
        return emailTextField;
    }
    public javax.swing.JTextField getAddressTextField(){
        return addressTextField;
    }
    public javax.swing.JTextField getPhoneNumberTextField(){
        return phoneNumberTextField;
    }
    public javax.swing.JPasswordField getSetPasswordTextField(){
        return setPasswordField;
    }
    public javax.swing.JPasswordField getConfirmPasswordTextField(){
        return confirmPasswordField;
    }
    public void toggleSetPasswordVisibility(ActionListener listener) {
    showButton.addActionListener(listener);
    }
    public void toggleConfirmPasswordVisibility(ActionListener listener) {
    confirmShowButton.addActionListener(listener);
    }


}

