/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package happytravell.view;

/**
 *
 * @author lenovo
 */
public class Customercare extends javax.swing.JFrame {

    /**
     * Creates new form Customercare
     */
    public Customercare() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        Emailfield = new javax.swing.JTextField();
        Namefield = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        Typefield = new javax.swing.JTextArea();
        jLabel10 = new javax.swing.JLabel();
        Sendfield = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/WhatsApp Image 2025-05-27 at 18.01.51_a4ab430b.jpg"))); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 0, 0));
        jLabel2.setText("CONTACT US");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(28, 14, 87, 20);

        jLabel3.setText("HOME");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(203, 17, 35, 16);

        jLabel4.setText("ABOUT US");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(264, 17, 56, 16);

        jLabel5.setText("BLOG");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(346, 17, 29, 16);

        jLabel6.setText("FQA");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(402, 17, 23, 16);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setText("HELLO,USERNAME");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(488, 14, 140, 20);

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setText("Full Name");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(70, 120, 70, 16);

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel9.setText("Email Address");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(70, 176, 100, 30);
        getContentPane().add(Emailfield);
        Emailfield.setBounds(70, 210, 221, 22);
        getContentPane().add(Namefield);
        Namefield.setBounds(70, 150, 221, 22);

        Typefield.setColumns(20);
        Typefield.setForeground(new java.awt.Color(102, 102, 102));
        Typefield.setRows(5);
        Typefield.setText("Type your message here......");
        jScrollPane1.setViewportView(Typefield);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(410, 70, 200, 200);

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 102));
        jLabel10.setText("Frequently Asked Questions");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(420, 50, 170, 16);

        Sendfield.setBackground(new java.awt.Color(0, 0, 51));
        Sendfield.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Sendfield.setForeground(new java.awt.Color(255, 255, 255));
        Sendfield.setText("Send Message");
        getContentPane().add(Sendfield);
        Sendfield.setBounds(450, 280, 130, 23);

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/WhatsApp Image 2025-05-27 at 18.01.51_a4ab430b.jpg"))); // NOI18N
        jLabel11.setText("jLabel11");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(0, 0, 687, 360);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Customercare.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Customercare.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Customercare.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Customercare.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Customercare().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Emailfield;
    private javax.swing.JTextField Namefield;
    private javax.swing.JButton Sendfield;
    private javax.swing.JTextArea Typefield;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
