/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package happytravell.view;
import happytravell.view.Register;
/**
 *
 * @author User
 */
public class loginPage extends javax.swing.JFrame {

    /**
     * Creates new form login
     */
    public loginPage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        wellcomeLabel = new javax.swing.JLabel();
        emailLabel = new javax.swing.JLabel();
        passwordLabel = new javax.swing.JLabel();
        emailTextField = new javax.swing.JTextField();
        jPasswordField1 = new javax.swing.JPasswordField();
        passwordShowToggleButton = new javax.swing.JToggleButton();
        loginButton = new javax.swing.JButton();
        forgotpasswordButton = new javax.swing.JButton();
        createAccountButton = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        wellcomeLabel.setFont(new java.awt.Font("Serif", 1, 23)); // NOI18N
        wellcomeLabel.setForeground(new java.awt.Color(0, 153, 0));
        wellcomeLabel.setText("Wellcome To Happy Travel");
        getContentPane().add(wellcomeLabel);
        wellcomeLabel.setBounds(330, 30, 280, 34);

        emailLabel.setText("Email/Username:");
        getContentPane().add(emailLabel);
        emailLabel.setBounds(330, 120, 90, 16);

        passwordLabel.setText("Password:");
        getContentPane().add(passwordLabel);
        passwordLabel.setBounds(370, 160, 53, 16);

        emailTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailTextFieldActionPerformed(evt);
            }
        });
        getContentPane().add(emailTextField);
        emailTextField.setBounds(430, 120, 170, 22);
        getContentPane().add(jPasswordField1);
        jPasswordField1.setBounds(430, 160, 110, 22);

        passwordShowToggleButton.setText("Show");
        passwordShowToggleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordShowToggleButtonActionPerformed(evt);
            }
        });
        getContentPane().add(passwordShowToggleButton);
        passwordShowToggleButton.setBounds(540, 160, 59, 23);

        loginButton.setText("Login");
        loginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginButtonActionPerformed(evt);
            }
        });
        getContentPane().add(loginButton);
        loginButton.setBounds(430, 220, 90, 23);

        forgotpasswordButton.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        forgotpasswordButton.setForeground(new java.awt.Color(0, 102, 255));
        forgotpasswordButton.setText("Forget password ?");
        forgotpasswordButton.setBorderPainted(false);
        forgotpasswordButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                forgotpasswordButtonActionPerformed(evt);
            }
        });
        getContentPane().add(forgotpasswordButton);
        forgotpasswordButton.setBounds(340, 310, 110, 20);

        createAccountButton.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        createAccountButton.setForeground(new java.awt.Color(0, 102, 255));
        createAccountButton.setText("Create Account");
        createAccountButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createAccountButtonActionPerformed(evt);
            }
        });
        getContentPane().add(createAccountButton);
        createAccountButton.setBounds(490, 310, 100, 20);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/WhatsApp Image 2025-05-22 at 10.03.44 PM.jpeg"))); // NOI18N
        getContentPane().add(jLabel4);
        jLabel4.setBounds(0, 0, 640, 360);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void emailTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailTextFieldActionPerformed

    private void passwordShowToggleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordShowToggleButtonActionPerformed
        // TODO add your handling code here:
        if (passwordShowToggleButton.isSelected()) {
        jPasswordField1.setEchoChar((char) 0); // show password
        passwordShowToggleButton.setText("Hide");
    } else {
        jPasswordField1.setEchoChar('●'); // hide password
        passwordShowToggleButton.setText("Show");
    }
    }//GEN-LAST:event_passwordShowToggleButtonActionPerformed

    private void forgotpasswordButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_forgotpasswordButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_forgotpasswordButtonActionPerformed

    private void createAccountButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createAccountButtonActionPerformed
        // TODO add your handling code here:
    Register register = new Register();
    register.setVisible(true);
    this.dispose(); // optional: closes the login window
    }//GEN-LAST:event_createAccountButtonActionPerformed

    private void loginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginButtonActionPerformed
                                              
    String enteredUsername = emailTextField.getText();
    String enteredPassword = new String(jPasswordField1.getPassword());

    // Hardcoded valid credentials
    String validUsername = "yaswant";
    String validPassword = "1234";

    if (enteredUsername.isEmpty() || enteredPassword.isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(this, "Please enter both username and password.");
    } else if (enteredUsername.equals(validUsername) && enteredPassword.equals(validPassword)) {
        javax.swing.JOptionPane.showMessageDialog(this, "Login successful!");
        // add Dashboard
        // new Dashboard(
    } else {
        javax.swing.JOptionPane.showMessageDialog(this, "Invalid username or password.");
    }
    }//GEN-LAST:event_loginButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(loginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(loginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(loginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(loginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new loginPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton createAccountButton;
    private javax.swing.JLabel emailLabel;
    private javax.swing.JTextField emailTextField;
    private javax.swing.JButton forgotpasswordButton;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JButton loginButton;
    private javax.swing.JLabel passwordLabel;
    private javax.swing.JToggleButton passwordShowToggleButton;
    private javax.swing.JLabel wellcomeLabel;
    // End of variables declaration//GEN-END:variables
}
