/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package happytravell.view;

import java.awt.event.ActionListener;



/**
 *
 * @author User
 */
public class LoginPageView extends javax.swing.JFrame {

    /**
     * Creates new form login
     */
    public LoginPageView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        wellcomeLabel = new javax.swing.JLabel();
        emailLabel = new javax.swing.JLabel();
        passwordLabel = new javax.swing.JLabel();
        emailTextField = new javax.swing.JTextField();
        passwordField = new javax.swing.JPasswordField();
        showButton = new javax.swing.JToggleButton();
        loginButton = new javax.swing.JButton();
        forgetPasswordButton = new javax.swing.JButton();
        createAccountButton = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        wellcomeLabel.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        wellcomeLabel.setText("Wellcome To Happy Travel");
        getContentPane().add(wellcomeLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 50, 260, 34));

        emailLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        emailLabel.setText("Email/Username:");
        getContentPane().add(emailLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 120, 100, -1));

        passwordLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        passwordLabel.setText("Password:");
        getContentPane().add(passwordLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 163, 60, -1));

        emailTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailTextFieldActionPerformed(evt);
            }
        });
        getContentPane().add(emailTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 120, 170, -1));
        getContentPane().add(passwordField, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 160, 110, -1));

        showButton.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        showButton.setText("Show");
        showButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showButtonActionPerformed(evt);
            }
        });
        getContentPane().add(showButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 160, 60, -1));

        loginButton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        loginButton.setText("Login");
        loginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginButtonActionPerformed(evt);
            }
        });
        getContentPane().add(loginButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 220, 90, 30));

        forgetPasswordButton.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        forgetPasswordButton.setForeground(new java.awt.Color(0, 102, 255));
        forgetPasswordButton.setText("Forget password ?");
        forgetPasswordButton.setBorderPainted(false);
        forgetPasswordButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                forgetPasswordButtonActionPerformed(evt);
            }
        });
        getContentPane().add(forgetPasswordButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 300, 130, 30));

        createAccountButton.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        createAccountButton.setForeground(new java.awt.Color(0, 102, 255));
        createAccountButton.setText("Create Account");
        createAccountButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createAccountButtonActionPerformed(evt);
            }
        });
        getContentPane().add(createAccountButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 300, 120, 30));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/WhatsApp Image 2025-05-22 at 10.03.44 PM.jpeg"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void emailTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailTextFieldActionPerformed

    private void showButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showButtonActionPerformed
                // TODO add your handling code here:
    }//GEN-LAST:event_showButtonActionPerformed

    private void forgetPasswordButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_forgetPasswordButtonActionPerformed
                // TODO add your handling code here:
    }//GEN-LAST:event_forgetPasswordButtonActionPerformed

    private void createAccountButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createAccountButtonActionPerformed
                // TODO add your handling code here:
    }//GEN-LAST:event_createAccountButtonActionPerformed

    private void loginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_loginButtonActionPerformed

    public static void main (String args[]){
        java.awt.EventQueue.invokeLater(new Runnable(){
            public void run (){
                new LoginPageView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton createAccountButton;
    private javax.swing.JLabel emailLabel;
    private javax.swing.JTextField emailTextField;
    private javax.swing.JButton forgetPasswordButton;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JButton loginButton;
    private javax.swing.JPasswordField passwordField;
    private javax.swing.JLabel passwordLabel;
    private javax.swing.JToggleButton showButton;
    private javax.swing.JLabel wellcomeLabel;
    // End of variables declaration//GEN-END:variables
    
    
    
    
    public javax.swing.JTextField getEmailTextField(){
        return emailTextField;
    }
    public javax.swing.JPasswordField getPasswordField(){
        return passwordField;
    }
    public void LoginUser(ActionListener listener){
        loginButton.addActionListener(listener);
    }
    public void CreateAccountNav(ActionListener listener){
        createAccountButton.addActionListener(listener);
    }
    public void ForgetPasswordNav(ActionListener listener){
        forgetPasswordButton.addActionListener(listener);
    }
}
