/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package happytravell.view;

import java.awt.Image;
import java.awt.event.ActionListener;
import java.awt.event.MouseListener;
import javax.swing.ImageIcon;
import javax.swing.JLabel;



/**
 *
 * @author User
 */
public class LoginPageView extends javax.swing.JFrame {

    /**
     * Creates new form login
     */
    public LoginPageView() {
        initComponents();
        
//        scaleImage1();
        
    }

//    public void scaleImage1(){
//        ImageIcon icon1 = new ImageIcon(getClass().getResource("/image/hide.png"));
//        //scaling image to fit in the hlabel.
//        Image img1 = icon1.getImage();
//        Image imgScale = img1.getScaledInstance(hideIcon.getWidth(), hideIcon.getHeight(), Image.SCALE_SMOOTH);
//        ImageIcon scaledIcon = new ImageIcon(imgScale);
//        hideIcon.setIcon(scaledIcon);
//    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        wellcomeLabel = new javax.swing.JLabel();
        emailLabel = new javax.swing.JLabel();
        passwordLabel = new javax.swing.JLabel();
        emailTextField = new javax.swing.JTextField();
        showButton = new javax.swing.JToggleButton();
        passwordField = new javax.swing.JPasswordField();
        loginButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        signUpLabel = new javax.swing.JLabel();
        forgetPasswordLabel = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        wellcomeLabel.setFont(new java.awt.Font("Candara", 1, 30)); // NOI18N
        wellcomeLabel.setForeground(new java.awt.Color(255, 153, 0));
        wellcomeLabel.setText("Travel Management System");
        getContentPane().add(wellcomeLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 40, 380, -1));

        emailLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        emailLabel.setText("  Email");
        getContentPane().add(emailLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 200, 60, 30));

        passwordLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        passwordLabel.setText("Password");
        getContentPane().add(passwordLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 250, 90, 30));

        emailTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailTextFieldActionPerformed(evt);
            }
        });
        getContentPane().add(emailTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 200, 220, 30));

        showButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        showButton.setText("Show");
        showButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showButtonActionPerformed(evt);
            }
        });
        getContentPane().add(showButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 250, 70, 30));

        passwordField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordFieldActionPerformed(evt);
            }
        });
        getContentPane().add(passwordField, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 250, 220, 30));

        loginButton.setBackground(new java.awt.Color(255, 153, 51));
        loginButton.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        loginButton.setForeground(new java.awt.Color(51, 51, 51));
        loginButton.setText("Login");
        loginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginButtonActionPerformed(evt);
            }
        });
        getContentPane().add(loginButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 320, 220, 33));

        jLabel1.setText("   Don't have an account ? ");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 360, 150, -1));

        signUpLabel.setText("   SignUp");
        getContentPane().add(signUpLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 360, 60, -1));

        forgetPasswordLabel.setText("   Forget Password ?");
        getContentPane().add(forgetPasswordLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 280, 120, 20));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/LoginFinal.png"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void emailTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailTextFieldActionPerformed

    private void loginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_loginButtonActionPerformed

    private void passwordFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordFieldActionPerformed

    private void showButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_showButtonActionPerformed

    public static void main (String args[]){
        java.awt.EventQueue.invokeLater(new Runnable(){
            public void run (){
                new LoginPageView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel emailLabel;
    private javax.swing.JTextField emailTextField;
    private javax.swing.JLabel forgetPasswordLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton loginButton;
    private javax.swing.JPasswordField passwordField;
    private javax.swing.JLabel passwordLabel;
    private javax.swing.JToggleButton showButton;
    private javax.swing.JLabel signUpLabel;
    private javax.swing.JLabel wellcomeLabel;
    // End of variables declaration//GEN-END:variables
    

    public String getEmail() {
        return emailTextField.getText();
    }

    public String getPassword() {
        return new String(passwordField.getPassword());
    }

    public javax.swing.JTextField getEmailTextField() {
        return emailTextField;
    }
    
    public javax.swing.JPasswordField getPasswordField() {
        return passwordField;
    }

    public javax.swing.JToggleButton getShowButton() {
        return showButton;
    }

    public JLabel getForgetPasswordLabel() {
        return forgetPasswordLabel;
    }

    public JLabel getSignupLabel() {
        return signUpLabel;
    }

    public void LoginUser(ActionListener listener) {
        loginButton.addActionListener(listener);
    }

    public void signUpNavigation(MouseListener listener) {
        signUpLabel.addMouseListener(listener);
    }

    public void ForgetPasswordNavigation(MouseListener listener) {
        forgetPasswordLabel.addMouseListener(listener);
    }
    
    public void TogglePasswordVisibility(ActionListener listener) {
        showButton.addActionListener(listener);
    }
}
