/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package happytravell.view;

/**
 *
 * @author Acer
 */
public class RegisterView extends javax.swing.JFrame {

    /**
     * Creates new form Register
     */
    public RegisterView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField2 = new javax.swing.JTextField();
        RegisterLabel = new javax.swing.JLabel();
        LastnameTextField = new javax.swing.JTextField();
        FirstnameTextField = new javax.swing.JTextField();
        UsernameTextField = new javax.swing.JTextField();
        registerButton = new javax.swing.JButton();
        backButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        lastnameLabel = new javax.swing.JLabel();
        setUsernamelabel = new javax.swing.JLabel();
        emailLabel = new javax.swing.JLabel();
        phonenumberLabel = new javax.swing.JLabel();
        addressLabel = new javax.swing.JLabel();
        setPassword = new javax.swing.JLabel();
        confirmpasswordlabel = new javax.swing.JLabel();
        firstnameLabel = new javax.swing.JLabel();
        EmailTextField = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        jPasswordField1 = new javax.swing.JPasswordField();
        jPasswordField2 = new javax.swing.JPasswordField();
        setshowButton = new javax.swing.JButton();
        confirmshowButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        jTextField2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextField2.setText("  Set Username");
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        RegisterLabel.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        RegisterLabel.setText("Register");
        getContentPane().add(RegisterLabel);
        RegisterLabel.setBounds(440, 20, 94, 31);

        LastnameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LastnameTextFieldActionPerformed(evt);
            }
        });
        getContentPane().add(LastnameTextField);
        LastnameTextField.setBounds(430, 100, 126, 22);

        FirstnameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FirstnameTextFieldActionPerformed(evt);
            }
        });
        getContentPane().add(FirstnameTextField);
        FirstnameTextField.setBounds(430, 70, 126, 22);

        UsernameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UsernameTextFieldActionPerformed(evt);
            }
        });
        getContentPane().add(UsernameTextField);
        UsernameTextField.setBounds(430, 130, 126, 22);

        registerButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        registerButton.setText("Register");
        getContentPane().add(registerButton);
        registerButton.setBounds(450, 317, 90, 27);

        backButton.setBackground(new java.awt.Color(239, 243, 243));
        backButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        backButton.setText("Back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });
        getContentPane().add(backButton);
        backButton.setBounds(350, 320, 70, 20);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 72, 0, 0);

        lastnameLabel.setText("Last name");
        getContentPane().add(lastnameLabel);
        lastnameLabel.setBounds(370, 103, 54, 16);

        setUsernamelabel.setText("Set Username");
        getContentPane().add(setUsernamelabel);
        setUsernamelabel.setBounds(350, 133, 80, 16);

        emailLabel.setText("Email");
        getContentPane().add(emailLabel);
        emailLabel.setBounds(393, 163, 30, 16);

        phonenumberLabel.setText("Phone number");
        getContentPane().add(phonenumberLabel);
        phonenumberLabel.setBounds(350, 193, 79, 16);

        addressLabel.setText("Address");
        getContentPane().add(addressLabel);
        addressLabel.setBounds(380, 223, 42, 16);

        setPassword.setText("Set Password");
        getContentPane().add(setPassword);
        setPassword.setBounds(353, 253, 70, 16);

        confirmpasswordlabel.setText("Confirm Password");
        getContentPane().add(confirmpasswordlabel);
        confirmpasswordlabel.setBounds(330, 280, 97, 16);

        firstnameLabel.setText("First name");
        getContentPane().add(firstnameLabel);
        firstnameLabel.setBounds(370, 73, 55, 16);

        EmailTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmailTextFieldActionPerformed(evt);
            }
        });
        getContentPane().add(EmailTextField);
        EmailTextField.setBounds(430, 160, 126, 22);

        jTextField8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField8ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField8);
        jTextField8.setBounds(430, 190, 126, 22);

        jTextField9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField9ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField9);
        jTextField9.setBounds(430, 220, 126, 22);

        jPasswordField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jPasswordField1);
        jPasswordField1.setBounds(430, 250, 126, 22);

        jPasswordField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordField2ActionPerformed(evt);
            }
        });
        getContentPane().add(jPasswordField2);
        jPasswordField2.setBounds(430, 280, 126, 22);

        setshowButton.setText("Show");
        getContentPane().add(setshowButton);
        setshowButton.setBounds(560, 253, 60, 23);

        confirmshowButton.setText("Show");
        getContentPane().add(confirmshowButton);
        confirmshowButton.setBounds(560, 280, 60, 23);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/registerBg.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, -4, 640, 370);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void FirstnameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FirstnameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FirstnameTextFieldActionPerformed

    private void UsernameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UsernameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UsernameTextFieldActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_backButtonActionPerformed

    private void LastnameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LastnameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LastnameTextFieldActionPerformed

    private void EmailTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmailTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EmailTextFieldActionPerformed

    private void jTextField8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField8ActionPerformed

    private void jTextField9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField9ActionPerformed

    private void jPasswordField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordField2ActionPerformed

    private void jPasswordField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordField1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegisterView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegisterView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegisterView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegisterView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegisterView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField EmailTextField;
    private javax.swing.JTextField FirstnameTextField;
    private javax.swing.JTextField LastnameTextField;
    private javax.swing.JLabel RegisterLabel;
    private javax.swing.JTextField UsernameTextField;
    private javax.swing.JLabel addressLabel;
    private javax.swing.JButton backButton;
    private javax.swing.JLabel confirmpasswordlabel;
    private javax.swing.JButton confirmshowButton;
    private javax.swing.JLabel emailLabel;
    private javax.swing.JLabel firstnameLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JPasswordField jPasswordField2;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JLabel lastnameLabel;
    private javax.swing.JLabel phonenumberLabel;
    private javax.swing.JButton registerButton;
    private javax.swing.JLabel setPassword;
    private javax.swing.JLabel setUsernamelabel;
    private javax.swing.JButton setshowButton;
    // End of variables declaration//GEN-END:variables
}
