/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package happytravell.view;

import java.awt.event.ActionListener;

/**
 *
 * @author Acer
 */
public class SignupAsView extends javax.swing.JFrame {

    /**
     * Creates new form SignupAs
     */
    public SignupAsView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        signupLabel = new javax.swing.JLabel();
        whichaccountLabel = new javax.swing.JLabel();
        adminButton = new javax.swing.JButton();
        travellerButton = new javax.swing.JButton();
        loginButton = new javax.swing.JButton();
        alreadyLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        signupLabel.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        signupLabel.setForeground(new java.awt.Color(204, 102, 0));
        signupLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        signupLabel.setText("Sign Up");
        getContentPane().add(signupLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 140, 110, -1));

        whichaccountLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        whichaccountLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        whichaccountLabel.setText("Which type of account do you want to sign up?");
        getContentPane().add(whichaccountLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 200, 350, -1));

        adminButton.setBackground(new java.awt.Color(255, 153, 51));
        adminButton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        adminButton.setText("Admin");
        adminButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminButtonActionPerformed(evt);
            }
        });
        getContentPane().add(adminButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 230, 200, -1));

        travellerButton.setBackground(new java.awt.Color(255, 153, 51));
        travellerButton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        travellerButton.setText("Traveller");
        travellerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                travellerButtonActionPerformed(evt);
            }
        });
        getContentPane().add(travellerButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 290, 200, -1));

        loginButton.setBackground(new java.awt.Color(255, 153, 51));
        loginButton.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        loginButton.setText("Login");
        loginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginButtonActionPerformed(evt);
            }
        });
        getContentPane().add(loginButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 380, 200, 33));

        alreadyLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        alreadyLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        alreadyLabel.setText("Already have account?");
        getContentPane().add(alreadyLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 350, 150, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/LoginFinal.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void adminButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_adminButtonActionPerformed

    private void travellerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_travellerButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_travellerButtonActionPerformed

    private void loginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_loginButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SignupAsView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SignupAsView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SignupAsView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SignupAsView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SignupAsView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton adminButton;
    private javax.swing.JLabel alreadyLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton loginButton;
    private javax.swing.JLabel signupLabel;
    private javax.swing.JButton travellerButton;
    private javax.swing.JLabel whichaccountLabel;
    // End of variables declaration//GEN-END:variables
public void adminNavigation(ActionListener listener){
        adminButton.addActionListener(listener);
    }
     

    public void travellerNavigation(ActionListener listener) {
        travellerButton.addActionListener(listener);
    }
    
    public void loginNavigation(ActionListener listener){
        loginButton.addActionListener(listener);
    }
    


}
