/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package happytravell.view;

/**
 *
 * @author Acer
 */
public class SignupAsView extends javax.swing.JFrame {

    /**
     * Creates new form SignupAs
     */
    public SignupAsView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        signupLabel = new javax.swing.JLabel();
        whichaccountLabel = new javax.swing.JLabel();
        adminButton = new javax.swing.JButton();
        passengerButton = new javax.swing.JButton();
        loginButton = new javax.swing.JButton();
        alreadyLabel = new javax.swing.JLabel();
        backButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        signupLabel.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        signupLabel.setText("Sign Up");
        getContentPane().add(signupLabel);
        signupLabel.setBounds(420, 50, 100, 32);

        whichaccountLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        whichaccountLabel.setText("Which type of account do you want to sign up?");
        getContentPane().add(whichaccountLabel);
        whichaccountLabel.setBounds(340, 110, 270, 16);

        adminButton.setBackground(new java.awt.Color(239, 243, 243));
        adminButton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        adminButton.setText("Admin");
        adminButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminButtonActionPerformed(evt);
            }
        });
        getContentPane().add(adminButton);
        adminButton.setBounds(400, 190, 129, 32);

        passengerButton.setBackground(new java.awt.Color(239, 243, 243));
        passengerButton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        passengerButton.setText("Passenger");
        passengerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passengerButtonActionPerformed(evt);
            }
        });
        getContentPane().add(passengerButton);
        passengerButton.setBounds(400, 140, 129, 32);

        loginButton.setBackground(new java.awt.Color(239, 243, 243));
        loginButton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        loginButton.setText("Login");
        loginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginButtonActionPerformed(evt);
            }
        });
        getContentPane().add(loginButton);
        loginButton.setBounds(430, 280, 83, 32);

        alreadyLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        alreadyLabel.setText("Already have account?");
        getContentPane().add(alreadyLabel);
        alreadyLabel.setBounds(410, 250, 127, 16);

        backButton.setBackground(new java.awt.Color(239, 243, 243));
        backButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        backButton.setText("Back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });
        getContentPane().add(backButton);
        backButton.setBounds(330, 290, 70, 20);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/signupAsBg.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, -4, 640, 370);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void adminButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_adminButtonActionPerformed

    private void passengerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passengerButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passengerButtonActionPerformed

    private void loginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_loginButtonActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_backButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SignupAsView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SignupAsView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SignupAsView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SignupAsView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SignupAsView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton adminButton;
    private javax.swing.JLabel alreadyLabel;
    private javax.swing.JButton backButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton loginButton;
    private javax.swing.JButton passengerButton;
    private javax.swing.JLabel signupLabel;
    private javax.swing.JLabel whichaccountLabel;
    // End of variables declaration//GEN-END:variables
}
